verison: '3.9'

services:
  client_app:
    container_name: connect-ui
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend_app
    networks:
      - client_backend_network

  backend_app:
    container_name: connect-api
    build:
      context: ./src
      dockerfile: Connect.WebAPI/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - db
    links:
      - db
    networks:
      - client_backend_network
      - backend_db_network
  
  db:
    container_name: connect-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    envirement:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=^potato2004$
    ports:
      - '1433: 1433'
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - backend_db_network

networks:
  client_backend_network:
  backend_db_network:
    internal: true
