version: '3.9'

services:
  client_app:
    container_name: connect-ui
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend_app
    networks:
      - client_backend_network

  backend_app:
    container_name: connect-api
    build:
      context: ./src
      dockerfile: Connect.WebAPI/Dockerfile
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$uper$trongP@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Connect.WebAPI.pfx
    depends_on:
      - db
    links:
      - db
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - client_backend_network
      - backend_db_network
  
  db:
    container_name: connect-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=^potato2004$
    ports:
      - '1433:1433'
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - backend_db_network

networks:
  client_backend_network:
  backend_db_network:
    internal: true
